### ISSUE TITLE
Recipe edit

### ISSUE THREAD

**Issue by shiyingzheng** [shiyingzheng/recipe_search#41]
The original author of the recipe should be able to edit the recipe.

**Comment by shangwyoung** [comment]
Getting a weird error when defining a foreign key in recipe to UserProfile:

^Caarony@aarony:~/recipe_search/cookin$ python3 manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f82a77ca0d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(_args, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(__exception)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(_args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python3.4/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.4/importlib/**init**.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/aarony/recipe_search/cookin/app/models/__init__.py", line 1, in <module>
    from .recipe_model import Recipe
  File "/home/aarony/recipe_search/cookin/app/models/recipe_model.py", line 4, in <module>
    from app.models import UserProfile
ImportError: cannot import name 'UserProfile'

Any Ideas?! @shiyingzheng

**Comment by shangwyoung** [comment]
Added the following 2 lines to recipe_model.py:

from app.models import UserProfile
recipe_owner = models.ForeignKey(UserProfile, related_name='uploaded_recipe')

**Comment by shangwyoung** [comment]
This line in recipe_models solved the problem:
recipe_owner = models.ForeignKey('UserProfile', blank=True, null=True,
                                        related_name='owner_recipe')

**Comment by shangwyoung** [comment]
Basic editing features (excluding custom written fields in model) working:

Source: http://stackoverflow.com/questions/26013270/django-update-form

**Comment by shiyingzheng** [comment]
Is this completed yet?

**Comment by shangwyoung** [comment]
Yes, it has just been completed! I have merged master into recipe_ownership branch, and minor merge conflicts that I've fixed. I have not yet made any migrations after merging master. Next steps would be to migrate and fix migrations. Perhaps you can help me with that? @shiyingzheng
